name: IssueTemplate
description: "This report is to present issues which need to be resolved and completed."
title: "[Issue]: "
labels: ["problem", "issue"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your issue in great detail!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If additional persons need to be notified or involved, please fill out the form.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: New issue
      description: Please provide as many details as possible to describe an issue
      placeholder: Type here the nature of the issue and what needs to be resolved.
      value: "The new issue is the following..."
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this issue?
      options:
        - Not urgent at all
        - Not very urgent
        - Somewhat urgent
        - Urgent
        - Very urgent
        - This takes prioritv over everything else
    validations:
      required: true
  - type: dropdown
    id: report
    attributes:
      label: Do you require progress report to be informed about how the issue is being solved?
      multiple: false
      options:
        - Do not require report at all
        - Require report only when complete
        - Require report only on major changes
        - Require report for any activity
